<!--
 * @Descripttion: 
 * @version: 
 * @Author: LiuZhiYi
 * @Date: 2023-08-13 11:15:49
 * @LastEditTime: 2023-08-13 13:25:11
-->
# 协程
- 协程是一个函数，它可以暂停以及恢复执行
- 协程的优点主要在于，它能优化异步逻辑的代码，使代码可读性更高
~~~c++
Task PrintInt() {

    IntReader reader1;
    int total = co_await reader1;

    IntReader reader2;
    total += co_await reader2;

    IntReader reader3;
    total += co_await reader3;

    std::cout << total << std::endl;
}
~~~

## 组成部分
- promise object：从协程内部操作；协程通过这个object提交结果或异常
- coroutine handle：从协程外部操作，这是一个非拥有句柄，用于恢复协程的执行或销毁协程帧
- coroutine state：这是内部的、动态分配的存储（除非分配被优化）
## 三个关键字
- 内部可以用co_await , co_yield.两个关键字挂起协程，co_return,关键字进行返回。
    - co_await调用一个awaiter对象（可以认为是一个接口），根据其内部定义决定其操作是挂起，还是继续，以及挂起，恢复时的行为    
    - 挂起协程。其出现形式是
    ~~~c
    co_yield  cy_ret;
    ~~~
    cy_ret会保存在promise承诺对象中（通过yield_value函数）。在协程外部可以通过promise得到。
    - cr_ret会保存在promise承诺对象中（通过return_value函数）。在协程外部可以通过promise得到。要注意，cr_ret并不是协程的返回值。这个是有区别的
## 执行过程
- allocates the coroutine state object using operator new.
- copies all function parameters to the coroutine state: by-value parameters are moved or copied, by-reference parameters remain references 
- calls the constructor for the promise object. If the promise type has a constructor that takes all coroutine parameters, that constructor is called, with post-copy coroutine arguments. Otherwise the default constructor is called.
- calls `promise.get_return_object()` and keeps the result in a local variable. The result of that call will be returned to the caller when the coroutine **first suspends**. Any exceptions thrown up to and including this step propagate back to the caller, not placed in the promise.
- calls `promise.initial_suspend()` and co_awaits its result. Typical Promise types either return a `std::suspend_always`, for lazily-started coroutines, or `std::suspend_never`, for eagerly-started coroutines.
- when co_await `promise.initial_suspend()` resumes, starts executing the body of the coroutine.
## promise
- 承诺对象是一个实现若干接口，用于辅助协程，构造协程函数返回值；提交传递co_yield，co_return的返回值。明确协程启动阶段是否立即挂起；以及协程内部发生异常时的处理方式
    - auto get_return_object() ：用于生成协程函数的返回对象。
    - auto initial_suspend()：用于明确初始化后，协程函数的执行行为，返回值为等待体（awaiter），用co_wait调用其返回值。返回值为std::suspend_always 表示协程启动后立即挂起（不执行第一行协程函数的代码），返回std::suspend_never 表示协程启动后不立即挂起。（当然既然是返回等待体，你可以自己在这儿选择进行什么等待操作）
    - void return_value(T v)：调用co_return v后会调用这个函数，可以保存co_return的结果
    - auto yield_value(T v)：调用co_yield后会调用这个函数，可以保存co_yield的结果，其返回其返回值为std::suspend_always表示协程会挂起，如果返回std::suspend_never表示不挂起。
    - auto final_suspend() noexcept：在协程退出是调用的接口，返回std::suspend_never ，自动销毁 coroutine state 对象。若 final_suspend 返回 std::suspend_always 则需要用户自行调用 handle.destroy() 进行销毁。但值得注意的是返回std::suspend_always并不会挂起协程。
## 协程句柄 (coroutine handle)
协程句柄的表现形式是std::coroutine_handle<promise_type>，其模板参数为承诺对象（promise）类型。句柄有几个重要函数：

- resume()函数可以恢复协程。
- done()函数可以判断协程是否已经完成。返回false标示协程还没有完成，还在挂起。
协程句柄和承诺对象之间是可以相互转化的。

- std::coroutine_handle<promise_type>::from_promise ： 这是一个静态函数，可以从承诺对象（promise）得到相应句柄。
- std::coroutine_handle<promise_type>::promise() 函数可以从协程句柄coroutine handle得到对应的承诺对象（promise）
## awaiter
co_wait 关键字会调用一个等待体对象(awaiter)。这个对象内部也有3个接口。根据接口co_wait 决定进行什么操作。

- bool await_ready()：等待体是否准备好了，返回 false ，表示协程没有准备好，立即调用await_suspend。返回true，表示已经准备好了。
- auto await_suspend(std::coroutine_handle<> handle)如果要挂起，调用的接口。其中handle参数就是调用等待体的协程，其返回值有3种可能
    - void 同返回true
    - bool 返回true 立即挂起，返回false 不挂起。
    - 返回某个协程句柄（coroutine handle），立即恢复对应句柄的运行。
- auto await_resume() ：协程挂起后恢复时，调用的接口。返回值作为co_wait 操作的返回值。

- std::suspend_never类，不挂起的的特化等待体类型。
- std::suspend_always类，挂起的特化等待体类型。
## co_await
- 挂起协程
- if await_suspend returns void, control is immediately returned to the caller/resumer of the current coroutine (this coroutine remains suspended), otherwise
- if await_suspend returns bool,
  - the value true returns control to the caller/resumer of the current coroutine
  - the value false resumes the current coroutine.
- if await_suspend returns a coroutine handle for some other coroutine, that handle is resumed (by a call to handle.resume()) 
- if await_suspend throws an exception, the exception is caught, the coroutine is resumed, and the exception is immediately re-thrown.
- Finally, awaiter.await_resume() is called (whether the coroutine was suspended or not), and **its result is the result of the whole co_await expr expression**.
~~~c++
#include <coroutine>
#include <iostream>
#include <stdexcept>
#include <thread>
 
auto switch_to_new_thread(std::jthread& out)
{
    struct awaitable
    {
        std::jthread* p_out;
        bool await_ready() { return false; }
        void await_suspend(std::coroutine_handle<> h)
        {
            std::jthread& out = *p_out;
            if (out.joinable())
                throw std::runtime_error("Output jthread parameter not empty");
            out = std::jthread([h] { h.resume(); });
            // Potential undefined behavior: accessing potentially destroyed *this
            // std::cout << "New thread ID: " << p_out->get_id() << '\n';
            std::cout << "New thread ID: " << out.get_id() << '\n'; // this is OK
        }
        void await_resume() {}
    };
    return awaitable{&out};
}
 
struct task
{
    struct promise_type
    {
        task get_return_object() { return {}; }
        std::suspend_never initial_suspend() { return {}; }
        std::suspend_never final_suspend() noexcept { return {}; }
        void return_void() {}
        void unhandled_exception() {}
    };
};
 
task resuming_on_new_thread(std::jthread& out)
{
    std::cout << "Coroutine started on thread: " << std::this_thread::get_id() << '\n';
    co_await switch_to_new_thread(out);
    // awaiter destroyed here
    std::cout << "Coroutine resumed on thread: " << std::this_thread::get_id() << '\n';
}
 
int main()
{
    std::jthread out;
    resuming_on_new_thread(out);
}
// Coroutine started on thread: 139972277602112
// New thread ID: 139972267284224
// Coroutine resumed on thread: 139972267284224
~~~

## co_yield
- 返回一个值同时挂起协程
- 相当于`co_await promise.yield_value(expr)`










